version: '3'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    env_file: .env
    depends_on:
      - db

  db:
    image: mysql:8.0.35
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: shoppingweb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./database:/docker-entrypoint-initdb.d

  # 可以添加其他服务，如 Nginx、Redis等
